Challenge = ["2 Box",
"No Jugg",
"Only Jugg",
"Melee Only",
"EE Speedrun",
"Pap all Weapons",
"321 Challenge",
"No Open Doors",
"Box Roulette",
"Explosives Only",
"Wall Weapons Only",
"No Pack-a-Punch",
"Olympia Only",
"Spawn Room"]
Map = ["Town",
"Farm",
"Tranzit",
"Bus Depot",
"Mob",
"Buried",
"Die Rise",
"Nuketown",
"Origins"]
bDescriptions = ["Quick Revive/Afterlife",
"Starting Pistol",
"Melee/Knifing",
"Melee/Knife Upgrades",
"Hells Retriever",
"Equipment",
"Non-lethal Buildables",
"Lethal Buildables"]
rangesList = ["953g145",
"1453g195",
"1953g245",
"2453g295",
"2953g345",
"3453g395",
"3953g445",
"4453g495"]
redGreen = ["darkred green green darkred darkred green green darkred",
"darkred green green green green green green green",
"darkred green green darkred green green green green",
"darkred darkred green green darkred darkred green darkred",
"green green green green green green green green",
"darkred green green green green green green green",
"darkred green green darkred darkred green green darkred",
"darkred green green darkred darkred green green green",
"darkred green green darkred darkred green green darkred",
"darkred darkred green darkred darkred green green green",
"darkred darkred darkred green darkred green green darkred",
"darkred green green darkred darkred green green darkred",
"darkred darkred green darkred darkred green green darkred",
"darkred green green darkred darkred green darkred darkred"]
