Challenge = ["2 Box",
"No Jugg",
"Only Jugg",
"Melee Only",
"EE Speedrun",
"Pap all Weapons",
"321 Challenge",
"No Open Doors",
"Box Roulette",
"Explosives Only",
"Wall Weapons Only",
"No Pack-a-Punch",
"Olympia Only",
"Spawn Room"]
Map = ["Town",
"Farm",
"Tranzit",
"Bus Depot",
"Mob",
"Buried",
"Die Rise",
"Nuketown",
"Origins"]
bDescriptions = ["Quick Revive/Afterlife",
"Starting Pistol",
"Melee/Knifing",
"Melee/Knife Upgrades",
"Hells Retriever",
"Equipment",
"Non-lethal Buildables",
"Lethal Buildables"]
rangesList = ["953g145",
"1453g195",
"1953g245",
"2453g295",
"2953g345",
"3453g395",
"3953g445",
"4453g495"]
redGreen = ["darkred green green darkred darkred green green darkred",
"darkred green green green green green green green",
"darkred green green darkred green green green green",
"darkred darkred green green darkred darkred green darkred",
"green green green green green green green green",
"darkred green green green green green green green",
"darkred green green darkred darkred green green darkred",
"darkred green green darkred darkred green green green",
"darkred green green darkred darkred green green darkred",
"darkred darkred green darkred darkred green green green",
"darkred darkred darkred green darkred green green darkred",
"darkred green green darkred darkred green green darkred",
"darkred darkred green darkred darkred green green darkred",
"darkred green green darkred darkred green darkred darkred"]
extraInfoDesc = ["Afterlife is fine if you kill yourself, but not if you die to zombies",
"You must eventually replace this gun in challenges that require you to use specific guns and have this enabled",
"This refers to your starting knife",
"This includes, Glavaknuckles, Bowie Knife, Silver Spoon, and The Golden Spork",
"Only applicable on Mob of the Dead",
"Grenades, EMP's, Monkeys, Time Bombs, and Claymores are all equipment items",
"Zombie Shield and trample steam are fine, as long as you dont attack with them",
"This is any buildable designed to kill"]
cDescriptions = ["Hit the box twice as fast as you can. You must use only those 2 weapons for the remainder of the game.",
"You are not allowed to buy Jugger-nog.",
"The only perk you are allowed to have is Jugger-nog.",
"You are not allowed to use guns, traps, or anything but your melee to kill zombies.",
"Complete the map's easter egg as fast as possible. Counted by round, not by time.",
"Pack-a-punch all weapons available on the map. Including the starting pistol.",
"3 Perks, 2 Box hits, 1 Pack-a-Punch. You can replace a box hit with a wall weapon, but you cannot re-pack.",
"You cannot spend any points to open doors. Doors unlocked by other means are fine.",
"Starting at Round 5 you must hit the box every round and use that weapon until it runs out of ammo or the round ends.",
"You must get an explosives weapon as fast as possible. After that you must only use that and other explosives weapons for the remainder of the game. Grenades count.",
"You cannot hit the box for a weapon. You must buy it off a wall. Bowie knife and Galvaknuckles count.",
"You are not allowed to use the Pack-a-Punch machine.",
"The only weapon you can use is the olympia. Pack-a-Punch'ing is fine.",
"You cannot leave the spawn area. The spawn area is anywhere you can get without triggering an event, like opening doors, falling down pits, etc."]